### PR TITLE
Updating dependencies to support pySigma 0.11.9

### PR DESCRIPTION
**Pull request by joshnck**
Updated dependencies but I had to disable two backends that are currently broken.

`pysigma-backend-cortexxdr` has an open issue explaining how to resolve the current problem (https://github.com/7RedViolin/pySigma-backend-cortexxdr/issues/15)

`pysigma-backend-insightidr` is disabled until the author actually publishes `0.2.3` which should be fully supported

### CODE REVIEW

**Comment by M3NIX** [comment]
Thank you for your contribution! Unfortunately the GitHub workflow for deploying seems to be broken. 

@josehelps could you have a look at it: https://github.com/magicsword-io/sigconverter.io/actions/runs/10047146202

**Comment by josehelps** [comment]
👀

**Comment by joshnck** [comment]
Ah -- it is an issue with `pysigma-backend-panther` which is failing when launching because it does not have the correct version of black :)

**Comment by josehelps** [comment]
FWIW looks like this introduced a issue, will try to build locally see what went wrong here is the errors I saw on cloud run side:

```
 Traceback (most recent call last):
  File "/app/./run.py", line 18, in <module>
    plugins = InstalledSigmaPlugins.autodiscover() 
```

saw a few updates in the deps might be due to that. Stay tune.

**Comment by josehelps** [comment]
@joshnck want to share a PR for that, get this fixed up?

**Comment by joshnck** [comment]
@josehelps  https://github.com/magicsword-io/sigconverter.io/pull/46 should do it. It is the lazy way around resolving the dependency issue though.

**Comment by M3NIX** [comment]
That worked :)
Should be live under https://beta.sigconverter.io/ now

**Comment by josehelps** [comment]
yay thank you @joshnck @M3NIX 🤘

**Pull request merged**
